In [7]:
# Libraries
import os
import sys
import pandas as pd
import numpy as np
import scipy.io

In [10]:
# Dataset
df = pd.read_csv('Dataset\\Data2024.xlsx - Monthly.csv')

In [ ]:
# this works
df

,yyyymm,price,d12,e12,ret,retx,AAA,BAA,lty,ltr,...,ygap,rdsp,rsvix,gpce,gip,tchi,house,avgcor,shtint,disag
0,187101,4.44,0.2600,0.4000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,187102,4.50,0.2600,0.4000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,187103,4.61,0.2600,0.4000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,187104,4.74,0.2600,0.4000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,187105,4.86,0.2600,0.4000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1843,202408,5648.40,72.9255,198.8233,0.024283,0.022898,0.0487,0.0560,0.0387,0.0128,...,-3.384681,0.034581,NaN,NaN,NaN,1.055849,NaN,0.195877,-1.884540,2.504554
1844,202409,5762.48,73.4003,200.2700,0.022821,0.021707,0.0468,0.0542,0.0372,0.0120,...,-3.395982,0.023585,NaN,NaN,NaN,1.055849,NaN,0.236572,-2.006363,2.263729
1845,202410,5705.45,73.8776,203.5700,-0.008690,-0.009523,0.0495,0.0563,0.0410,-0.0238,...,-3.373349,0.029564,NaN,NaN,NaN,1.055849,NaN,0.256120,-2.057976,2.846782
1846,202411,6032.38,74.3549,206.8700,0.060420,0.059016,0.0514,0.0578,0.0436,0.0078,...,-3.415483,0.040457,NaN,NaN,NaN,1.055849,NaN,0.176644,-2.078823,3.231256
1847,202412,5881.63,74.8323,210.1700,-0.023445,-0.024621,0.0520,0.0580,0.0439,-0.0154,...,-3.374636,0.029925,NaN,NaN,NaN,1.055849,NaN,0.195351,-2.135697,2.824905

In [ ]:
# We are concered with 8 variables

# We are concered with the time period 

# January 1948 to December 2021

In [14]:
type(df['yyyymm'][0])

numpy.int64

In [15]:
df = df[df['yyyymm'] >= 194801]
df = df[df['yyyymm'] <= 202112]

In [16]:
df

,yyyymm,price,d12,e12,ret,retx,AAA,BAA,lty,ltr,...,ygap,rdsp,rsvix,gpce,gip,tchi,house,avgcor,shtint,disag
924,194801,14.69,0.8433,1.6433,-0.037743,-0.038905,0.0286,0.0352,0.0243,0.0020,...,NaN,0.038914,NaN,NaN,NaN,NaN,NaN,0.205305,NaN,NaN
925,194802,14.00,0.8467,1.6767,-0.040232,-0.047782,0.0285,0.0353,0.0241,0.0046,...,NaN,0.030306,NaN,NaN,NaN,NaN,NaN,0.281183,NaN,NaN
926,194803,15.08,0.8500,1.7100,0.081440,0.077022,0.0283,0.0353,0.0241,0.0034,...,NaN,0.037562,NaN,NaN,NaN,NaN,NaN,0.335241,NaN,NaN
927,194804,15.48,0.8500,1.7600,0.030821,0.028537,0.0278,0.0347,0.0239,0.0045,...,NaN,0.036490,NaN,NaN,NaN,NaN,NaN,0.302520,NaN,NaN
928,194805,16.69,0.8500,1.8100,0.084014,0.077523,0.0276,0.0338,0.0231,0.0141,...,NaN,0.037955,NaN,NaN,NaN,NaN,NaN,0.218204,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1807,202108,4522.68,58.7913,169.8333,0.030600,0.029205,0.0255,0.0324,0.0128,-0.0035,...,-3.294761,0.022097,0.021794,NaN,NaN,1.055849,NaN,0.199031,-1.758543,4.652412
1808,202109,4307.54,59.2545,175.3700,-0.046077,-0.047152,0.0253,0.0323,0.0137,-0.0250,...,-3.214831,0.034246,0.047692,NaN,NaN,1.055849,NaN,0.249149,-1.760424,4.919234
1809,202110,4605.38,59.6354,182.8700,0.070510,0.069627,0.0268,0.0335,0.0158,0.0051,...,-3.241936,0.026553,0.023831,NaN,NaN,1.055849,NaN,0.245633,-1.723666,5.594355
1810,202111,4567.00,60.0162,190.3700,-0.007256,-0.008666,0.0262,0.0328,0.0156,0.0210,...,-3.193227,0.035130,0.062986,NaN,NaN,1.055849,NaN,0.247123,-1.820190,4.653923
1811,202112,4766.18,60.3971,197.8700,0.043485,0.042285,0.0265,0.0330,0.0147,-0.0110,...,-3.196435,0.039192,0.024679,NaN,NaN,1.055849,NaN,0.251053,-1.886112,4.601180

In [ ]:
# Dividend-price ratio (d/p)
# Default yield spread (dfy)
# Term spread (tms)
# Treasury bill rate (tbl)
# Long-term government bond return (ltr)
# Default return spread (dfr)
# Net equity expansion (ntis)
# Inflation (infl)


prdictors = ['d/p', 'dfy', 'tms', 'tbl', 'ltr', 'dfr', 'ntis', 'infl']

In [21]:
# 57 columns
list(df.columns)

['yyyymm',
 'price',
 'd12',
 'e12',
 'ret',
 'retx',
 'AAA',
 'BAA',
 'lty',
 'ltr',
 'corpr',
 'tbl',
 'Rfree',
 'd/p',
 'd/y',
 'e/p',
 'd/e',
 'b/m',
 'tms',
 'dfy',
 'dfr',
 'infl',
 'eqis',
 'ntis',
 'svar',
 'cay',
 'i/k',
 'csp',
 'pce',
 'vp',
 'impvar',
 'vrp',
 'govik',
 'lzrt',
 'skew',
 'crdstd',
 'ogap',
 'wtexas',
 'accrul',
 'cfacc',
 'sntm',
 'ndrbl',
 'skvw',
 'tail',
 'fbm',
 'dtoy',
 'dtoat',
 'ygap',
 'rdsp',
 'rsvix',
 'gpce',
 'gip',
 'tchi',
 'house',
 'avgcor',
 'shtint',
 'disag']

In [24]:
X = df[prdictors]